<a href="https://colab.research.google.com/github/melissagaleanot-crypto/entregable-pandas-numpy/blob/main/notebooks_py/Limpieza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
dataframe_url = 'https://www.datos.gov.co/resource/a7iv-sme8.json'
df = pd.read_json(dataframe_url)
df.head()

,atc,principioactivo,descripcionatc,producto,expediente,registrosanitario,fechavencimiento,estadoregistro,descripcioncomercial,unidad,viaadministracion,concentracion,unidadmedida,cantidad,unidadreferencia,formafarmaceutica,nombrerol
0,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,Vigente,CAJA DESIN DATOCARTÓN CONSIN DATOFRASCOSIN DAT...,ml,CONJUNTIVAL,C,mg,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA S.A. DE C.V.
1,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,Vigente,CAJA DESIN DATOCARTÓN CONSIN DATOFRASCOSIN DAT...,ml,CONJUNTIVAL,C,mg,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA DE COLOMBIA LTDA.
2,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,Vigente,MUESTRA MEDICA :CAJASIN DATOCONSIN DATOUN FRAS...,ml,CONJUNTIVAL,C,mg,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA DE COLOMBIA LTDA.
3,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,Vigente,MUESTRA MEDICA :CAJASIN DATOCONSIN DATOUN FRAS...,ml,CONJUNTIVAL,C,mg,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA S.A. DE C.V.
4,D08AC52,ALCOHOL ETILICO AL 92.44% EQUIVALENTE A ALCOHO...,CLORHEXIDINA COMBINACIONES,3M AVAGARD,19948203,INVIMA 2016M-0005076-R1,NaN,Vigente,BOTELLA DE POLIETILENO DE ALTA DENSIDAD DE 500...,U,TOPICA (EXTERNA),B,g,65.78,100 G,SOLUCION TOPICA,ACCUPAC INC.

In [5]:
#Valores asociados a cadenas de texto
conteo_principio_activo = df['principioactivo'].value_counts()
print(conteo_principio_activo) #Array por clave & valor

principioactivo
ACETAMINOFEN                                                 88
ACETAMINOFÉN PAP 90% EQUIVALENTE A ACETAMINOFÉN              81
CAFEINA ANHIDRA                                              70
ACETAMINOFEN 87% EQUIVALENTE A ACETAMINOFEN                  65
ACETILCISTEINA                                               32
                                                             ..
702 MG DE ABACAVIR SULFATO. EQUIVALENTE ABACAVIR              2
ACETAMINOFEN DCI 90% 1111.00MG EQUIVALENTE A ACETAMINOFEN     2
CLORHIDRATO DE DIFENHIDRAMINA                                 1
PARACETAMOL (ACETAMINOFEN)                                    1
HIDROCODONA BITARTRATO                                        1
Name: count, Length: 73, dtype: int64

In [6]:
#Valores Asociados a forma farmaceutica
forma_contador = df['formafarmaceutica'].value_counts()
print(forma_contador)

formafarmaceutica
TABLETA                                                      301
CAPSULA BLANDA                                               210
TABLETA RECUBIERTA                                           202
TABLETA EFERVESCENTE                                          50
SOLUCION TOPICA                                               36
SUSPENSION INYECTABLE                                         36
SOLUCION INYECTABLE                                           32
JARABE                                                        20
TABLETA CUBIERTA CON PELICULA                                 20
CAPSULA DURA                                                  16
SOLUCIÓN CONCENTRADA PARA INFUSIÓN                            14
GRANULOS                                                      10
SOLUCION ORAL                                                  9
SOLUCION OTICA                                                 8
UNGUENTO TOPICO                                                8
SUSPENSION ORAL                                                6
POLVO LIOFILIZADO PARA RECONSTITUIR A SOLUCION INYECTABLE      6
GEL TOPICO                                                     5
SOLUCION OFTALMICA                                             4
OVULO                                                          4
CREMA TOPICA                                                   3
Name: count, dtype: int64

In [7]:
print("NORMALIZACION DE VALORES")
df['principioactivo'] = df['principioactivo'].str.upper()
df['formafarmaceutica'] = df['formafarmaceutica'].str.upper()
df['descripcionatc'] = df['descripcionatc'].str.upper()
df['unidadmedida'] = df['unidadmedida'].str.upper()
df['estadoregistro'] = df['estadoregistro'].str.upper()
df.head()

NORMALIZACION DE VALORES

,atc,principioactivo,descripcionatc,producto,expediente,registrosanitario,fechavencimiento,estadoregistro,descripcioncomercial,unidad,viaadministracion,concentracion,unidadmedida,cantidad,unidadreferencia,formafarmaceutica,nombrerol
0,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,VIGENTE,CAJA DESIN DATOCARTÓN CONSIN DATOFRASCOSIN DAT...,ml,CONJUNTIVAL,C,MG,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA S.A. DE C.V.
1,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,VIGENTE,CAJA DESIN DATOCARTÓN CONSIN DATOFRASCOSIN DAT...,ml,CONJUNTIVAL,C,MG,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA DE COLOMBIA LTDA.
2,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,VIGENTE,MUESTRA MEDICA :CAJASIN DATOCONSIN DATOUN FRAS...,ml,CONJUNTIVAL,C,MG,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA DE COLOMBIA LTDA.
3,S01BC03,DICLOFENACO SODICO,DICLOFENAC,3- A OFTENO,230339,INVIMA 2008 M-012122 R-1,01/01/3000,VIGENTE,MUESTRA MEDICA :CAJASIN DATOCONSIN DATOUN FRAS...,ml,CONJUNTIVAL,C,MG,1.00,MILILITRO,SOLUCION OFTALMICA,LABORATORIOS SOPHIA S.A. DE C.V.
4,D08AC52,ALCOHOL ETILICO AL 92.44% EQUIVALENTE A ALCOHO...,CLORHEXIDINA COMBINACIONES,3M AVAGARD,19948203,INVIMA 2016M-0005076-R1,NaN,VIGENTE,BOTELLA DE POLIETILENO DE ALTA DENSIDAD DE 500...,U,TOPICA (EXTERNA),B,G,65.78,100 G,SOLUCION TOPICA,ACCUPAC INC.

In [8]:
print("Manejo de valores nulos")
print("Conteo de columnas antes de limpiar valores nulos")
columnas_antes = len(df.columns)
print(f"Cantidad de columnas antes de la limpieza: {columnas_antes}")
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100

print("Mostrar columnas con valores nulos:")
print("Porcentaje de valores nulos por columna:")
for columna, porcentaje in porcentaje_nulos.items():
    if porcentaje > 0:
        print(f"{columna}: {porcentaje:.2f}%")

print("Eliminar columnas con más de 50% de valores nulos")
df_limpio = df.loc[:, porcentaje_nulos <= 50]

print("Conteo de columnas despues de limpiar valores nulos")
columnas_despues = len(df_limpio.columns)
print(f"cantidad de columnas después de la limpieza: {columnas_despues}")
print(f"Columnas que se eliminaron: {columnas_antes - columnas_despues}")
print()

print("Columnas que quedaron:")
print(df_limpio.columns.tolist())

Manejo de valores nulos
Conteo de columnas antes de limpiar valores nulos
Cantidad de columnas antes de la limpieza: 17
Mostrar columnas con valores nulos:
Porcentaje de valores nulos por columna:
fechavencimiento: 73.10%
unidadreferencia: 0.40%
Eliminar columnas con más de 50% de valores nulos
Conteo de columnas despues de limpiar valores nulos
cantidad de columnas después de la limpieza: 16
Columnas que se eliminaron: 1

Columnas que quedaron:
['atc', 'principioactivo', 'descripcionatc', 'producto', 'expediente', 'registrosanitario', 'estadoregistro', 'descripcioncomercial', 'unidad', 'viaadministracion', 'concentracion', 'unidadmedida', 'cantidad', 'unidadreferencia', 'formafarmaceutica', 'nombrerol']

In [9]:
print("Filtrado por top 10 de categorías terapéuticas más importantes")
top_10_categorias = df_limpio['descripcionatc'].value_counts().head(10)

print("Categorías incluidas:")
print(top_10_categorias)
print()

df_filtrado = df_limpio[df_limpio['descripcionatc'].isin(top_10_categorias.index)]
print(f"Registros en top 15 categorías: {len(df_filtrado)}")

Filtrado por top 10 de categorías terapéuticas más importantes
Categorías incluidas:
descripcionatc
PARACETAMOL COMBINACIONES EXCLUYENDO SICOLEPTICOS    291
PARACETAMOL                                          167
CODEINA Y PARACETAMOL                                 88
ACETILCISTEINA                                        60
ABIRATERONA                                           39
DEXAMETASONA                                          36
VITAMINAS A Y D EN COMBINACION                        36
ADALIMUMAB                                            32
ETORICOXIB                                            32
PARACETAMOL. COMBINACIONES CON PSICOLECTICOS          30
Name: count, dtype: int64

Registros en top 15 categorías: 811